### ISSUE TITLE
tests/test_item.py fails with TypeError: a bytes-like object is required, not 'list'

### ISSUE THREAD

**Issue by zrhoffman** [mitya57/secretstorage#16]
Using `cryptography` version 2.5. Stack trace:

```shell
Traceback (most recent call last):
  File "/home/zrhoffman/github.com/python/mitya57/secretstorage/tests/test_item.py", line 59, in test_secret
    self.assertEqual(self.item.get_secret(), b'pa$$word')
  File "/home/zrhoffman/github.com/python/mitya57/secretstorage/secretstorage/item.py", line 106, in get_secret
    padded_secret = decryptor.update(encrypted_secret) + decryptor.finalize()
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
TypeError: a bytes-like object is required, not 'list'
```

This broke from [3c68250ad9 in pyca/cryptography](https://github.com/pyca/cryptography/commit/3c68250ad9#diff-7f9182acb7dedf7b702ac6c6b98fd678R138) because [`ffi.from_buffer()` needs an object which supports the buffer interface](https://cffi.readthedocs.io/en/release-1.11/ref.html#ffi-buffer-ffi-from-buffer), which lists do not. This change is reflected in `cryptography` version 2.5 but not version 2.4.2.

<details><summary>Full log (click to expand)</summary>

```shell
[zrhoffman@computer secretstorage]$ python3 -m unittest discover -s tests
../usr/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..sssss.........../usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=10, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/tokenize.py:376: ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/1000/bus>
  return readline()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
E..s
======================================================================
ERROR: test_secret (test_item.ItemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zrhoffman/github.com/python/mitya57/secretstorage/tests/test_item.py", line 59, in test_secret
    self.assertEqual(self.item.get_secret(), b'pa$$word')
  File "/home/zrhoffman/github.com/python/mitya57/secretstorage/secretstorage/item.py", line 106, in get_secret
    padded_secret = decryptor.update(encrypted_secret) + decryptor.finalize()
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
TypeError: a bytes-like object is required, not 'list'

----------------------------------------------------------------------
Ran 24 tests in 0.634s

FAILED (errors=1, skipped=6)
[zrhoffman@computer secretstorage]$ exit
```
</details>

**Comment by mitya57** [comment]
@rsyring New release 3.1.1 is now done!
